[project]
name = "ozon_price_monitoring"
version = "0.1.0"
description = "Ozon Price Tracker Bot"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.22.0",
    "aiosqlite>=0.21.0",
    "apscheduler>=3.11.0",
    "dotenv>=0.9.9",
    "playwright>=1.55.0",
]
